[package]
name = "sprite-demo-bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"

[[bin]]
name = "sprite-demo"
path = "main.rs"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = "thin"

[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = "fat"
codegen-units = 1
